apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.8.4
    chart: minio
    helm:
      values: |
        auth:
          rootUser: minio_access_key
          rootPassword: minio_secret_key
        defaultBuckets: "tiny, warehouse"
  destination:
    server: https://kubernetes.default.svc
    namespace: trino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 