apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-metastore-postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.5.8
    chart: postgresql
    helm:
      values: |
        auth:
          username: hive
          database: metastore
          password: hive
  destination:
    server: https://kubernetes.default.svc
    namespace: trino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 