apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-metastore-postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vndv/trino-k8s.git
    targetRevision: HEAD
    chart: postgresql
    helm:
      valueFiles:
        - hive-metastore-postgresql/values.yaml
      parameters:
        - name: chart.repository
          value: https://charts.bitnami.com/bitnami
        - name: chart.version
          value: "12.5.8"
  destination:
    server: https://kubernetes.default.svc
    namespace: trino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 