apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-metastore-postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "*"
    chart: postgresql
    helm:
      valueFiles:
        - values.yaml
      values: |
        {{- .Files.Get "hive-metastore-postgresql/values.yaml" | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: trino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 