image:
  repository: rtdl/hive-metastore
  tag: 3.1.2
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: "1Gi"
    cpu: "500m"
  requests:
    memory: "512Mi"
    cpu: "250m"

conf:
  hiveSite:
    hive.metastore.uris: thrift://hive-metastore:9083

extraEnvVars:
  - name: JAVA_OPTS
    value: "-Xmx512m -Xms256m"

waitDb:
  enabled: true
  image:
    repository: busybox
    tag: latest
    pullPolicy: IfNotPresent

hiveMetastoreDb:
  host: hive-metastore-postgresql
  port: 5432
